window.STORY_DATA = window.STORY_DATA || {};
Object.assign(window.STORY_DATA, {
  "Blur": "<<set $darkness += 5>>\n\n进了家门，你脱掉高跟鞋，揉了揉自己有些酸痛的小腿和脚踝。今晚的热闹好像还在皮肤下滚动，耳朵里的嗡鸣已经消散殆尽，身上缭绕的复杂味道在房间中开始弥散，你又想起夏以昼身上那股淡淡的皮革味。是你在其他人身上没有闻到过的香水。你思考了一会，向新好友发了消息：\n\n [[继续->Chat_Caleb2]]",
  "Blur_A1": "对方的对话框变成了正在输入中，却许久没有回信。你想大概是他误触了对话框吧，就把手机放在一边，走进浴室。氤氲的水汽随着热水的冲下而升腾，又让你想起舞台上迷幻的烟雾，夏以昼的轮廓在其中若隐若现，鼓棒翻飞，唯独那双紫色的眸子清晰可见。\n\n[[擦头发->Chat_Caleb3]]",
  "Blur-A1": "你对夏以昼的迷恋很快变成了一种习惯。\n\n乐团小号的夏以昼练习视频也被你刷的包浆，通勤的时候耳机里是Skyline的音乐，比起主唱的声音，你会用耳朵去抓伴奏中的鼓点声，凭借着你可怜的一次现场演出经验去想象夏以昼打鼓的样子——手臂的弧度、汗水滑过额角、紫色眸子在灯光下的闪动。你已经想象了太多次，甚至觉得他的脸在脑海中变得模糊，像被烟雾笼罩的剪影，唯独那双眼睛始终清晰。\n\n很快，马上就是下一场live的抢票时间了\n\n<<if $draws is undefined>><<set $draws = 0>><</if>>\n<<if $wins  is undefined>><<set $wins  = 0>><</if>>\n\n<div class=\"ticket-app\">\n  <div class=\"ticket-head\">\n    <span>Skyline Horizon</span>\n    <strong>LIVE</strong>\n  </div>\n  <div class=\"ticket-card\">\n    <div class=\"ticket-date\">NEXT SHOW</div>\n    <div class=\"ticket-title\">第二场演出</div>\n    <div class=\"ticket-meta\">前排余票刷新中</div>\n  </div>\n  <div id=\"draw-result\" class=\"ticket-result\">点击下方按钮抽票（70% 概率）。</div>\n<<button \"开始抢票\">>\n\t<<set $draws += 1>>\n\t<<set _roll to random(1,100)>>\n\t<<replace \"#draw-result\">><div class=\"ticket-loading\">正在连接票务系统……</div><</replace>>\n\t<<if _roll <= 70>>\n\t\t<<set $wins += 1>>\n\t\t<<replace \"#draw-result\">>\n\t\t<div class=\"ticket-success\">✅ 恭喜抢到！（本次: <<= _roll >>）</div>\n\t\t<br><span class=\"ticket-count\">已抢 <<= $draws >> 次，抢到 <<= $wins >> 次。</span>\n\t\t<</replace>>\n\t\t<<replace \"#ticket-continue\">>[[继续->Blur-A2]]<</replace>>\n\t<<else>>\n\t\t<<replace \"#draw-result\">>\n\t\t<div class=\"ticket-fail\">❌ 没抢到（本次: <<= _roll >>）。再试一次？</div>\n\t\t<br><span class=\"ticket-count\">已抢 <<= $draws >> 次，抢到 <<= $wins >> 次。</span>\n\t\t<</replace>>\n\t<</if>>\n<</button>>\n</div>\n<div id=\"ticket-continue\" class=\"phone-complete phone-complete-outside\"></div>",
  "Blur-A2": "<<set $favorCaleb += 5>>\n你跟Caleb关系变得热络了起来。虽然他的回复克制冷静，但是你总觉得他能精准地明白你的想法，还会给你分享一些其他人在网上也没说过的夏以昼的细节，比如他演出前喜欢喝加了柠檬汁的冰美式，喜欢在后台偷偷玩手机游戏。有了Caleb的细节补充，这些琐碎的小事像拼图碎片，夏以昼的形象不再只是你脑海中被烟雾蒙住的人形与视频中的侧影，渐渐拼凑成一个有血有肉的人。\n你在过去的练习视频中，好不容易截到了一张夏以昼打完鼓正面面对镜头的画面，有些模糊，但是紫色的眼睛清晰可见。你把这张截图设为了壁纸，对下一场演出抱有了无限的期待。\n[[第二场演出->Blur-A3]]",
  "Blur-A3": "第二场演出如期而至。\n\n【出门前你选择】\n[[精心打扮->Blur-B1]]\n[[普通装扮->Blur-B2]]",
  "Blur-B1": "<<set $favorYizhou += 2>> \n<<set $darkness += 1>>\n<<set $path = \"fancy\">> \n\n你鬼使神差地精心打扮了一番，在朴素的牛仔外套下穿了件性感的露背包臀裙，甚至喷了许久未用的香水。你站在第二排，视线牢牢锁在夏以昼身上。他的鼓点像心跳，敲在你胸口，每一下都带着炽热的节奏。\n\n[[继续->Blur-C1]]",
  "Blur-B2": "<<set $path = \"casual\">>\n你站在第二排，视线牢牢锁在夏以昼身上。他的鼓点像心跳，敲在你胸口，每一下都带着炽热的节奏。\n[[继续->Blur-C1]]",
  "Blur-C1": "灯光扫过舞台，他的紫色眸子在烟雾中时隐时现，你总觉得他的目光若有若无地飘向你，但是你又捕捉不到。你屏住呼吸，贪婪地用目光锁住夏以昼的每一个动作。演出结束，掌声如潮，你的心却还在鼓点里沉浮。\n乐队没有立刻离开，而是站在吧台一侧，看起了另一组乐队的表演。\n[[继续->Blur-C2]]",
  "Blur-C2": "夏以昼站在队员们稍远的地方，背靠墙壁，手里拿着一瓶水，略显疏离。他的脸因为演出的汗水微微反着光，你并看不清他脸上的表情。\n\n【你选择】\n[[去吧台旁边点一杯饮料->Blur-D1]]\n[[回家->Blur-E1]]",
  "Blur-D1": "<<set $favorYizhou += 2>> \n你在吧台的另一侧坐下，依照着习惯向酒保又要了一杯软饮，咬着吸管小口啜饮，目光却忍不住追随夏以昼。几个熟识的老粉走过去跟乐队成员打招呼，笑声和寒暄在空气中交织。\n\n\n你坐在远处，羡慕他们的轻松，却只敢远远地望着他们。台上的乐队表演结束，其他成员还在跟粉丝聊得热烈，夏以昼似乎跟其他队员说了什么，提前转身离开，背影消失在后台的暗门里。盯着那个方向，心底泛起一丝失落，既然他走了，你在这里继续待着也没什么意思。\n[[回家->Blur-E1]]",
  "Blur-E1": "回到家，你迫不及待地打开手机，点开Caleb的对话框，激动地分享今晚的演出。\n\n[[继续->Chat_Caleb4]]",
  "Blur-E2": "<<set $favorCaleb+= 2>> \n<<set $darkness += 1>>\n\n你盯着屏幕，试图从这行字里拼凑出Caleb的模样，可脑海里只有一片模糊。你也没多想，觉得大概是网友的心灵感应。你继续沉浸在今晚的迷幻快乐中，耳边仿佛还回荡着夏以昼的鼓点，皮肤下依然滚动着舞台的热浪。你把手机放在床上，准备洗漱。\n\n \n\n却没注意到对话框中，不断跳起的“正在输入中”。几秒后，提示消失，什么消息也没有，就像舞台灯光暗下后，留下的只有一片意味深长的沉寂。\n\n[[继续->Caleb-1]]",
  "Chat_Caleb2": "<div id=\"chat-caleb2\" class=\"phone-shell\" data-contact=\"Caleb\"></div>\n<script>\nrenderPhoneChat({\n  id: \"chat-caleb2\",\n  messages: [\n    { who: \"right\", text: \"你知道他用的香水是哪一款吗？\" }\n  ],\n  nextText: \"继续\",\n  nextTarget: \"Blur_A1\"\n});\n</script>",
  "Chat_Caleb3": "<div id=\"chat-caleb3\" class=\"phone-shell\" data-contact=\"Caleb\"></div>\n<script>\nrenderPhoneChat({\n  id: \"chat-caleb3\",\n  messages: [\n    { who: \"right\", text: \"你知道他用的香水是哪一款吗？\" },\n    { who: \"left\",  text: \"【图片】\", image: \"assets/perfume.jpg\", fallbackImage: \"file:///E:/codex/openclaw/assets/perfume.jpg\" },\n    { who: \"left\",  text: \"好像是这个\" },\n    { who: \"right\", text: \"谢谢，有机会我去看看\" },\n    { who: \"right\", text: \"我该怎么称呼你\" },\n    { who: \"left\",  text: \"Caleb\" }\n  ],\n  nextText: \"继续\",\n  nextTarget: \"Blur-A1\"\n});\n</script>",
  "Chat_Caleb4": "<div id=\"chat-caleb4\" class=\"phone-shell\" data-contact=\"Caleb\"></div>\n<<if $path is \"casual\">>\n<script>\nrenderPhoneChat({\n  id: \"chat-caleb4\",\n  messages: [\n    { who: \"right\", text: \"夏以昼今晚的鼓solo太炸了！感觉他好像看了我一眼，不过可能是我想多了，哈哈。\" },\n    { who: \"right\", text: \"而且他转鼓棒的样子真的好帅啊啊啊啊啊怎么有人手指那么长那么好看！还是前排好，能看到这么多细节。\" },\n    { who: \"right\", text: \"下次我还要抢前排！\" },\n    { who: \"left\",  text: \"哈哈，他肯定看了你。站在第二排，那离得很近了。\" },\n    { who: \"right\", text: \"你也在现场？\" },\n    { who: \"left\",  text: \"嗯，我每场都会去。没想到真的是你。\" }\n  ],\n  nextText: \"继续\",\n  nextTarget: \"Blur-E2\"\n});\n</script>\n<<else>>\n<script>\nrenderPhoneChat({\n  id: \"chat-caleb4\",\n  messages: [\n    { who: \"right\", text: \"夏以昼今晚的鼓solo太炸了！感觉他好像看了我一眼，不过可能是我想多了，哈哈。\" },\n    { who: \"right\", text: \"而且他转鼓棒的样子真的好帅啊啊啊啊啊怎么有人手指那么长那么好看！还是前排好，能看到这么多细节。\" },\n    { who: \"right\", text: \"下次我还要抢前排！\" },\n    { who: \"left\",  text: \"哈哈，他肯定看了你。站在第二排，那离得很近了。\" },\n    { who: \"left\", text: \"我今天好像看到你了，连衣裙很好看。\" },\n    { who: \"right\", text: \"你也在现场？\" },\n    { who: \"left\",  text: \"嗯，我每场都会去。没想到真的是你。\" }\n  ],\n  nextText: \"继续\",\n  nextTarget: \"Blur-E2\"\n});\n</script>\n<</if>>"
});
